export type SpeakingLocale = 'en' | 'ru' | 'ka';
type Localized = Record<SpeakingLocale, string>;

export type SpeakingScenario = {
  prompt: Localized;
  options: string[];
  correct: number;
  meaning: Localized;
};

export type SpeakingStep = {
  number: number;
  unit: number;
  kind: 'lesson' | 'review' | 'scenario' | 'mission';
  title: Localized;
  subtitle: Localized;
  minutes: number;
  words: string[];
  scenarios?: SpeakingScenario[];
};

const t = (en: string, ru: string, ka: string): Localized => ({ en, ru, ka });

export const speakingUnitTitles: Record<number, Localized> = {
  1: t('First conversations', 'Первые разговоры', 'პირველი საუბრები'),
  2: t('Café confidence', 'Уверенно в кафе', 'თავდაჯერებულად კაფეში'),
  3: t('Shop with confidence', 'Покупки без стресса', 'ყიდვა თავდაჯერებულად'),
  4: t('Find your way', 'Найдите дорогу', 'გაიკვლიეთ გზა'),
  5: t('Home and neighbours', 'Дом и соседи', 'სახლი და მეზობლები'),
  6: t('Work and services', 'Работа и услуги', 'სამსახური და სერვისები'),
  7: t('Health and pharmacy', 'Здоровье и аптека', 'ჯანმრთელობა და აფთიაქი'),
  8: t('Friends and plans', 'Друзья и планы', 'მეგობრები და გეგმები'),
};

export const speakingUnit: SpeakingStep[] = [
  {
    number: 1,
    unit: 1,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Hello and be polite',
      'Приветствие и вежливость',
      'მისალმება და თავაზიანობა',
    ),
    subtitle: t(
      'Open every conversation well.',
      'Начинайте разговор правильно.',
      'სწორად დაიწყეთ საუბარი.',
    ),
    words: ['გამარჯობა', 'მადლობა', 'გთხოვთ'],
  },
  {
    number: 2,
    unit: 1,
    kind: 'lesson',
    minutes: 5,
    title: t('React naturally', 'Отвечайте естественно', 'უპასუხეთ ბუნებრივად'),
    subtitle: t(
      'Say yes, no, good, and bad.',
      'Скажите: да, нет, хорошо и плохо.',
      'თქვით: კი, არა, კარგი და ცუდი.',
    ),
    words: ['ბოდიში', 'კი', 'დიახ', 'არა', 'კარგი', 'ცუდი'],
  },
  {
    number: 3,
    unit: 1,
    kind: 'lesson',
    minutes: 6,
    title: t('Meet someone', 'Познакомьтесь', 'გაიცანით ვინმე'),
    subtitle: t(
      'Talk about you and your name.',
      'Скажите о себе и своём имени.',
      'თქვით ვინ ხართ და რა გქვიათ.',
    ),
    words: ['მე', 'თქვენ', 'ჩემი', 'სახელი', 'მეგობარი'],
  },
  {
    number: 4,
    unit: 1,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Keep the conversation going',
      'Продолжите разговор',
      'გააგრძელეთ საუბარი',
    ),
    subtitle: t(
      'Understand, ask again, and slow things down.',
      'Попросите повторить или говорить медленнее.',
      'სთხოვეთ გამეორება ან ნელა საუბარი.',
    ),
    words: ['როგორ', 'მესმის', 'ისევ', 'ნელა', 'გაიმეორე'],
  },
  {
    number: 5,
    unit: 1,
    kind: 'review',
    minutes: 5,
    title: t(
      'Memory Check · First talk',
      'Проверка памяти · Знакомство',
      'მეხსიერება · გაცნობა',
    ),
    subtitle: t(
      'Recall the language without hints.',
      'Вспомните слова без подсказок.',
      'გაიხსენეთ სიტყვები მინიშნებების გარეშე.',
    ),
    words: [
      'გამარჯობა',
      'მადლობა',
      'გთხოვთ',
      'ბოდიში',
      'კი',
      'არა',
      'მე',
      'თქვენ',
      'სახელი',
      'ნელა',
    ],
  },
  {
    number: 6,
    unit: 1,
    kind: 'mission',
    minutes: 5,
    title: t(
      'Mission · Meet a neighbour',
      'Миссия · Знакомство с соседом',
      'მისია · მეზობლის გაცნობა',
    ),
    subtitle: t(
      'Complete your first useful exchange.',
      'Проведите первый полезный диалог.',
      'დაასრულეთ პირველი სასარგებლო საუბარი.',
    ),
    words: [],
    scenarios: [
      {
        prompt: t(
          'Greet your neighbour.',
          'Поздоровайтесь с соседом.',
          'მიესალმეთ მეზობელს.',
        ),
        options: ['გამარჯობა', 'ცუდი', 'არა'],
        correct: 0,
        meaning: t('Hello', 'Здравствуйте', 'გამარჯობა'),
      },
      {
        prompt: t(
          'Say: “My name is David.”',
          'Скажите: «Меня зовут Давид».',
          'თქვით: „მე მქვია დავითი“.',
        ),
        options: ['თქვენ დავით', 'მე მქვია დავითი', 'ჩემი კარგი'],
        correct: 1,
        meaning: t(
          'My name is David.',
          'Меня зовут Давид.',
          'მე მქვია დავითი.',
        ),
      },
      {
        prompt: t(
          'Ask them to speak slowly.',
          'Попросите говорить медленнее.',
          'სთხოვეთ ნელა ისაუბრონ.',
        ),
        options: ['ცუდი, მადლობა', 'არა, სახელი', 'ნელა, გთხოვთ'],
        correct: 2,
        meaning: t(
          'Slowly, please.',
          'Медленнее, пожалуйста.',
          'ნელა, გთხოვთ.',
        ),
      },
    ],
  },
  {
    number: 7,
    unit: 2,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Say what you need',
      'Скажите, что вам нужно',
      'თქვით, რა გჭირდებათ',
    ),
    subtitle: t(
      'Express hunger, thirst, wants, and needs.',
      'Скажите, что вы хотите или что вам нужно.',
      'თქვით, რა გინდათ ან გჭირდებათ.',
    ),
    words: ['მინდა', 'მჭირდება', 'მშია', 'მწყურია', 'შეიძლება'],
  },
  {
    number: 8,
    unit: 2,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Drinks you will actually order',
      'Напитки, которые вы закажете',
      'სასმელები, რომლებსაც შეუკვეთავთ',
    ),
    subtitle: t(
      'Coffee, tea, water, milk, and juice.',
      'Кофе, чай, вода, молоко и сок.',
      'ყავა, ჩაი, წყალი, რძე და წვენი.',
    ),
    words: ['ყავა', 'ჩაი', 'წყალი', 'რძე', 'წვენი'],
  },
  {
    number: 9,
    unit: 2,
    kind: 'lesson',
    minutes: 7,
    title: t(
      'Build a simple order',
      'Составьте простой заказ',
      'შეადგინეთ მარტივი შეკვეთა',
    ),
    subtitle: t(
      'Choose food and say what you like.',
      'Выберите еду и скажите, что вам нравится.',
      'აირჩიეთ საჭმელი და თქვით, რა მოგწონთ.',
    ),
    words: ['საჭმელი', 'პური', 'ყველი', 'სალათი', 'მომწონს'],
  },
  {
    number: 10,
    unit: 2,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Pay and finish',
      'Оплатите и завершите',
      'გადაიხადეთ და დაასრულეთ',
    ),
    subtitle: t(
      'Ask the price and choose card or cash.',
      'Узнайте цену и выберите карту или наличные.',
      'იკითხეთ ფასი და აირჩიეთ ბარათი ან ნაღდი.',
    ),
    words: ['რამდენი', 'ფასი', 'ფული', 'ბარათი', 'ნაღდი'],
  },
  {
    number: 11,
    unit: 2,
    kind: 'review',
    minutes: 5,
    title: t(
      'Memory Check · Café',
      'Проверка памяти · Кафе',
      'მეხსიერება · კაფე',
    ),
    subtitle: t(
      'Recall the order before the mission.',
      'Вспомните заказ перед миссией.',
      'გაიხსენეთ შეკვეთა მისიის წინ.',
    ),
    words: [
      'მინდა',
      'მშია',
      'მწყურია',
      'ყავა',
      'ჩაი',
      'წყალი',
      'პური',
      'სალათი',
      'ფასი',
      'ბარათი',
    ],
  },
  {
    number: 12,
    unit: 2,
    kind: 'mission',
    minutes: 6,
    title: t(
      'Mission · Order at a café',
      'Миссия · Заказ в кафе',
      'მისია · შეკვეთა კაფეში',
    ),
    subtitle: t(
      'Order, respond, and pay.',
      'Закажите, ответьте и оплатите.',
      'შეუკვეთეთ, უპასუხეთ და გადაიხადეთ.',
    ),
    words: [],
    scenarios: [
      {
        prompt: t(
          'Order coffee politely.',
          'Вежливо закажите кофе.',
          'თავაზიანად შეუკვეთეთ ყავა.',
        ),
        options: ['ყავა მინდა, გთხოვთ', 'ყავა ცუდი', 'ჩემი ყავა'],
        correct: 0,
        meaning: t(
          'I would like coffee, please.',
          'Я хочу кофе, пожалуйста.',
          'ყავა მინდა, გთხოვთ.',
        ),
      },
      {
        prompt: t(
          'Ask for water too.',
          'Попросите ещё воду.',
          'წყალიც ითხოვეთ.',
        ),
        options: ['წყალი არა', 'წყალიც, გთხოვთ', 'მე წყალი'],
        correct: 1,
        meaning: t(
          'Water too, please.',
          'И воду, пожалуйста.',
          'წყალიც, გთხოვთ.',
        ),
      },
      {
        prompt: t(
          'Ask if you may pay by card.',
          'Спросите, можно ли оплатить картой.',
          'იკითხეთ, შეიძლება თუ არა ბარათით გადახდა.',
        ),
        options: ['ბარათი ცუდი?', 'რამდენი ყავა?', 'ბარათით შეიძლება?'],
        correct: 2,
        meaning: t(
          'Can I pay by card?',
          'Можно оплатить картой?',
          'ბარათით შეიძლება?',
        ),
      },
      {
        prompt: t(
          'Finish politely.',
          'Завершите вежливо.',
          'თავაზიანად დაასრულეთ.',
        ),
        options: ['მადლობა', 'მშია', 'რამდენი'],
        correct: 0,
        meaning: t('Thank you.', 'Спасибо.', 'მადლობა.'),
      },
    ],
  },
  {
    number: 13,
    unit: 3,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Shopping essentials',
      'Главное для покупок',
      'მთავარი საყიდლებისთვის',
    ),
    subtitle: t(
      'Find the shop, item, and price.',
      'Найдите магазин, товар и цену.',
      'იპოვეთ მაღაზია, ნივთი და ფასი.',
    ),
    words: ['მაღაზია', 'ვეძებ', 'ეს', 'რა', 'ღირს'],
  },
  {
    number: 14,
    unit: 3,
    kind: 'lesson',
    minutes: 6,
    title: t('Choose an amount', 'Выберите количество', 'აირჩიეთ რაოდენობა'),
    subtitle: t(
      'Use small numbers, bottles, and bags.',
      'Используйте числа, бутылки и пакеты.',
      'გამოიყენეთ რიცხვები, ბოთლები და ჩანთები.',
    ),
    words: ['ერთი', 'ორი', 'სამი', 'ბოთლი', 'ჩანთა'],
  },
  {
    number: 15,
    unit: 3,
    kind: 'lesson',
    minutes: 7,
    title: t('Fill your basket', 'Наполните корзину', 'შეავსეთ კალათა'),
    subtitle: t(
      'Buy common food without searching a dictionary.',
      'Купите обычные продукты без словаря.',
      'იყიდეთ ყოველდღიური პროდუქტები ლექსიკონის გარეშე.',
    ),
    words: ['ხილი', 'ბოსტნეული', 'ვაშლი', 'კვერცხი', 'ხორცი'],
  },
  {
    number: 16,
    unit: 3,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Handle the checkout',
      'Разберитесь на кассе',
      'გადაიხადეთ სალაროსთან',
    ),
    subtitle: t(
      'Compare prices, pay, and ask for a receipt.',
      'Сравните цены, оплатите и попросите чек.',
      'შეადარეთ ფასები, გადაიხადეთ და მოითხოვეთ ქვითარი.',
    ),
    words: ['ძვირი', 'იაფი', 'ვიხდი', 'ხურდა', 'ქვითარი'],
  },
  {
    number: 17,
    unit: 3,
    kind: 'review',
    minutes: 5,
    title: t(
      'Memory Check · Shopping',
      'Проверка памяти · Покупки',
      'მეხსიერება · საყიდლები',
    ),
    subtitle: t(
      'Retrieve the language needed at checkout.',
      'Вспомните слова, нужные на кассе.',
      'გაიხსენეთ სალაროსთან საჭირო სიტყვები.',
    ),
    words: [
      'მაღაზია',
      'ვეძებ',
      'რა',
      'ღირს',
      'ერთი',
      'ბოთლი',
      'ხილი',
      'ვაშლი',
      'იაფი',
      'ქვითარი',
    ],
  },
  {
    number: 18,
    unit: 3,
    kind: 'mission',
    minutes: 7,
    title: t(
      'Mission · Shop independently',
      'Миссия · Покупки самостоятельно',
      'მისია · იყიდეთ დამოუკიდებლად',
    ),
    subtitle: t(
      'Find, choose, ask the price, and pay.',
      'Найдите, выберите, узнайте цену и оплатите.',
      'იპოვეთ, აირჩიეთ, იკითხეთ ფასი და გადაიხადეთ.',
    ),
    words: [],
    scenarios: [
      {
        prompt: t(
          'Say you are looking for water.',
          'Скажите, что ищете воду.',
          'თქვით, რომ წყალს ეძებთ.',
        ),
        options: ['წყალი ძვირია', 'წყალს ვეძებ', 'წყალი არა'],
        correct: 1,
        meaning: t('I am looking for water.', 'Я ищу воду.', 'წყალს ვეძებ.'),
      },
      {
        prompt: t(
          'Ask for two bottles.',
          'Попросите две бутылки.',
          'ითხოვეთ ორი ბოთლი.',
        ),
        options: ['ორი ბოთლი, გთხოვთ', 'ერთი ჩანთა', 'სამი ვაშლი'],
        correct: 0,
        meaning: t(
          'Two bottles, please.',
          'Две бутылки, пожалуйста.',
          'ორი ბოთლი, გთხოვთ.',
        ),
      },
      {
        prompt: t(
          'Ask: “How much is this?”',
          'Спросите: «Сколько это стоит?»',
          'იკითხეთ: „ეს რა ღირს?“',
        ),
        options: ['ეს სად არის?', 'რამდენი ბოთლი?', 'ეს რა ღირს?'],
        correct: 2,
        meaning: t('How much is this?', 'Сколько это стоит?', 'ეს რა ღირს?'),
      },
      {
        prompt: t(
          'Ask for the receipt.',
          'Попросите чек.',
          'მოითხოვეთ ქვითარი.',
        ),
        options: ['ხურდა ძვირია', 'ქვითარი, გთხოვთ', 'ბარათი არა'],
        correct: 1,
        meaning: t(
          'The receipt, please.',
          'Чек, пожалуйста.',
          'ქვითარი, გთხოვთ.',
        ),
      },
    ],
  },
  {
    number: 19,
    unit: 4,
    kind: 'lesson',
    minutes: 6,
    title: t('Places around you', 'Места вокруг вас', 'ადგილები თქვენ გარშემო'),
    subtitle: t(
      'Find streets, stops, pharmacies, and the centre.',
      'Найдите улицу, остановку, аптеку и центр.',
      'იპოვეთ ქუჩა, გაჩერება, აფთიაქი და ცენტრი.',
    ),
    words: ['სად', 'ქუჩა', 'გაჩერება', 'აფთიაქი', 'ცენტრი'],
  },
  {
    number: 20,
    unit: 4,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Understand directions',
      'Поймите направление',
      'გაიგეთ მიმართულება',
    ),
    subtitle: t(
      'Go right, left, straight, near, or far.',
      'Идите направо, налево, прямо, близко или далеко.',
      'წადით მარჯვნივ, მარცხნივ, პირდაპირ, ახლოს ან შორს.',
    ),
    words: ['მარჯვნივ', 'მარცხნივ', 'პირდაპირ', 'ახლოს', 'შორს'],
  },
  {
    number: 21,
    unit: 4,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Use city transport',
      'Пользуйтесь транспортом',
      'იმგზავრეთ ქალაქში',
    ),
    subtitle: t(
      'Recognize buses, taxis, stations, and tickets.',
      'Узнайте автобус, такси, станцию и билет.',
      'იცანით ავტობუსი, ტაქსი, სადგური და ბილეთი.',
    ),
    words: ['ავტობუსი', 'ტაქსი', 'სადგური', 'ბილეთი', 'მძღოლი'],
  },
  {
    number: 22,
    unit: 4,
    kind: 'lesson',
    minutes: 7,
    title: t(
      'Ask and recover',
      'Спросите и не потеряйтесь',
      'იკითხეთ და არ დაიკარგოთ',
    ),
    subtitle: t(
      'Explain where you are going and ask for help.',
      'Объясните, куда идёте, и попросите помощи.',
      'თქვით, სად მიდიხართ და ითხოვეთ დახმარება.',
    ),
    words: ['მივდივარ', 'დამეხმარეთ', 'მაჩვენე', 'მისამართი', 'რუკა'],
  },
  {
    number: 23,
    unit: 4,
    kind: 'review',
    minutes: 5,
    title: t(
      'Memory Check · Getting around',
      'Проверка памяти · Дорога',
      'მეხსიერება · გადაადგილება',
    ),
    subtitle: t(
      'Recall directions before the final mission.',
      'Вспомните направления перед финальной миссией.',
      'გაიხსენეთ მიმართულებები საბოლოო მისიის წინ.',
    ),
    words: [
      'სად',
      'გაჩერება',
      'აფთიაქი',
      'მარჯვნივ',
      'მარცხნივ',
      'პირდაპირ',
      'ავტობუსი',
      'ტაქსი',
      'დამეხმარეთ',
      'მისამართი',
    ],
  },
  {
    number: 24,
    unit: 4,
    kind: 'mission',
    minutes: 7,
    title: t(
      'Mission · Cross the city',
      'Миссия · Доберитесь через город',
      'მისია · გაიარეთ ქალაქი',
    ),
    subtitle: t(
      'Ask for a place and follow the answer.',
      'Спросите дорогу и поймите ответ.',
      'იკითხეთ გზა და გაიგეთ პასუხი.',
    ),
    words: [],
    scenarios: [
      {
        prompt: t(
          'Ask where the bus stop is.',
          'Спросите, где автобусная остановка.',
          'იკითხეთ, სად არის ავტობუსის გაჩერება.',
        ),
        options: [
          'ავტობუსი რა ღირს?',
          'ავტობუსის გაჩერება სად არის?',
          'ტაქსი მინდა',
        ],
        correct: 1,
        meaning: t(
          'Where is the bus stop?',
          'Где автобусная остановка?',
          'ავტობუსის გაჩერება სად არის?',
        ),
      },
      {
        prompt: t(
          'You hear “პირდაპირ”. Which way?',
          'Вы слышите «პირდაპირ». Куда идти?',
          'გესმით „პირდაპირ“. საით უნდა წახვიდეთ?',
        ),
        options: ['მარცხნივ', 'უკან', 'პირდაპირ'],
        correct: 2,
        meaning: t('Go straight.', 'Идите прямо.', 'წადით პირდაპირ.'),
      },
      {
        prompt: t(
          'Ask whether the centre is far.',
          'Спросите, далеко ли центр.',
          'იკითხეთ, ცენტრი შორს არის თუ არა.',
        ),
        options: ['ცენტრი შორს არის?', 'ცენტრი რა ღირს?', 'ცენტრი მარცხნივ'],
        correct: 0,
        meaning: t('Is the centre far?', 'Центр далеко?', 'ცენტრი შორს არის?'),
      },
      {
        prompt: t(
          'You are lost. Ask for help.',
          'Вы потерялись. Попросите помощи.',
          'დაიკარგეთ. ითხოვეთ დახმარება.',
        ),
        options: ['კარგი მისამართი', 'არა, პირდაპირ', 'დამეხმარეთ, გთხოვთ'],
        correct: 2,
        meaning: t(
          'Please help me.',
          'Помогите, пожалуйста.',
          'დამეხმარეთ, გთხოვთ.',
        ),
      },
    ],
  },
  {
    number: 25,
    unit: 5,
    kind: 'lesson',
    minutes: 6,
    title: t('Your home', 'Ваш дом', 'თქვენი სახლი'),
    subtitle: t(
      'Talk about rooms, doors, and keys.',
      'Говорите о комнатах, дверях и ключах.',
      'ისაუბრეთ ოთახებზე, კარებსა და გასაღებებზე.',
    ),
    words: ['სახლი', 'ოთახი', 'კარი', 'გასაღები', 'შიგნით'],
  },
  {
    number: 26,
    unit: 5,
    kind: 'lesson',
    minutes: 6,
    title: t('Daily life at home', 'Дела дома', 'ყოველდღიური ცხოვრება სახლში'),
    subtitle: t(
      'Describe a simple daily routine.',
      'Опишите простой распорядок дня.',
      'აღწერეთ მარტივი ყოველდღიური რუტინა.',
    ),
    words: ['ვცხოვრობ', 'ვიღვიძებ', 'ვდგები', 'ვიძინებ', 'ვბრუნდები'],
  },
  {
    number: 27,
    unit: 5,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Solve a home problem',
      'Решите проблему дома',
      'მოაგვარეთ პრობლემა სახლში',
    ),
    subtitle: t(
      'Point out what needs attention.',
      'Объясните, что требует внимания.',
      'თქვით, რას სჭირდება ყურადღება.',
    ),
    words: ['შუქი', 'ფანჯარა', 'აბაზანა', 'წყალი', 'ლიფტი'],
  },
  {
    number: 28,
    unit: 5,
    kind: 'lesson',
    minutes: 6,
    title: t('Welcome a guest', 'Встретьте гостя', 'მიიღეთ სტუმარი'),
    subtitle: t(
      'Help someone feel at home.',
      'Помогите гостю освоиться.',
      'დაეხმარეთ სტუმარს თავი შინ იგრძნოს.',
    ),
    words: ['სტუმარი', 'სკამი', 'მაგიდა', 'სამზარეულო', 'სუფთა'],
  },
  {
    number: 29,
    unit: 5,
    kind: 'review',
    minutes: 5,
    title: t(
      'Memory Check · Home',
      'Проверка памяти · Дом',
      'მეხსიერება · სახლი',
    ),
    subtitle: t(
      'Bring home language back to mind.',
      'Вспомните слова для дома.',
      'გაიხსენეთ სახლის სიტყვები.',
    ),
    words: [
      'სახლი',
      'ოთახი',
      'კარი',
      'გასაღები',
      'ვცხოვრობ',
      'შუქი',
      'აბაზანა',
      'სტუმარი',
      'სამზარეულო',
    ],
  },
  {
    number: 30,
    unit: 5,
    kind: 'mission',
    minutes: 6,
    title: t(
      'Mission · Help a neighbour',
      'Миссия · Помогите соседу',
      'მისია · დაეხმარეთ მეზობელს',
    ),
    subtitle: t(
      'Handle a small conversation at home.',
      'Проведите короткий разговор дома.',
      'წარმართეთ მოკლე საუბარი სახლში.',
    ),
    words: [],
    scenarios: [
      {
        prompt: t(
          'Say: “I live here.”',
          'Скажите: «Я живу здесь».',
          'თქვით: „მე აქ ვცხოვრობ“.',
        ),
        options: ['აქ ვცხოვრობ', 'აქ ვიძინებ', 'სახლი შორს'],
        correct: 0,
        meaning: t('I live here.', 'Я живу здесь.', 'აქ ვცხოვრობ.'),
      },
      {
        prompt: t('Ask for the key.', 'Попросите ключ.', 'ითხოვეთ გასაღები.'),
        options: ['კარი, მადლობა', 'გასაღები, გთხოვთ', 'ოთახი არა'],
        correct: 1,
        meaning: t(
          'The key, please.',
          'Ключ, пожалуйста.',
          'გასაღები, გთხოვთ.',
        ),
      },
      {
        prompt: t(
          'Show where the bathroom is.',
          'Покажите, где ванная.',
          'აჩვენეთ, სად არის აბაზანა.',
        ),
        options: ['აბაზანა აქ არის', 'ლიფტი შორს არის', 'წყალი მინდა'],
        correct: 0,
        meaning: t(
          'The bathroom is here.',
          'Ванная здесь.',
          'აბაზანა აქ არის.',
        ),
      },
    ],
  },
  {
    number: 31,
    unit: 6,
    kind: 'lesson',
    minutes: 6,
    title: t('Work basics', 'Главное на работе', 'მთავარი სამსახურში'),
    subtitle: t(
      'Say where and how you work.',
      'Скажите, где и как вы работаете.',
      'თქვით, სად და როგორ მუშაობთ.',
    ),
    words: ['ვმუშაობ', 'ოფისი', 'ვიწყებ', 'ვამთავრებ', 'დაკავებული'],
  },
  {
    number: 32,
    unit: 6,
    kind: 'lesson',
    minutes: 6,
    title: t('Arrange a time', 'Договоритесь о времени', 'შეთანხმდით დროზე'),
    subtitle: t(
      'Use today, tomorrow, hours, and minutes.',
      'Используйте сегодня, завтра, часы и минуты.',
      'გამოიყენეთ დღეს, ხვალ, საათი და წუთი.',
    ),
    words: ['დღეს', 'ხვალ', 'საათი', 'წუთი', 'ველოდები'],
  },
  {
    number: 33,
    unit: 6,
    kind: 'lesson',
    minutes: 6,
    title: t('Call and reply', 'Позвоните и ответьте', 'დარეკეთ და უპასუხეთ'),
    subtitle: t(
      'Handle a short work message.',
      'Разберитесь с коротким рабочим сообщением.',
      'უპასუხეთ მოკლე სამუშაო შეტყობინებას.',
    ),
    words: ['ვურეკავ', 'ვპასუხობ', 'შეტყობინება', 'ტელეფონი', 'ნომერი'],
  },
  {
    number: 34,
    unit: 6,
    kind: 'lesson',
    minutes: 7,
    title: t(
      'Use everyday services',
      'Пользуйтесь услугами',
      'გამოიყენეთ ყოველდღიური სერვისები',
    ),
    subtitle: t(
      'Ask for help at a bank or office.',
      'Попросите помощи в банке или офисе.',
      'ითხოვეთ დახმარება ბანკში ან ოფისში.',
    ),
    words: ['ბანკი', 'მისამართი', 'ბარათი', 'ვიღებ', 'ვაძლევ'],
  },
  {
    number: 35,
    unit: 6,
    kind: 'review',
    minutes: 5,
    title: t(
      'Memory Check · Work',
      'Проверка памяти · Работа',
      'მეხსიერება · სამსახური',
    ),
    subtitle: t(
      'Recall words for schedules and services.',
      'Вспомните слова для работы и услуг.',
      'გაიხსენეთ სამუშაოსა და სერვისების სიტყვები.',
    ),
    words: [
      'ვმუშაობ',
      'ოფისი',
      'დღეს',
      'ხვალ',
      'საათი',
      'ვურეკავ',
      'შეტყობინება',
      'ბანკი',
      'მისამართი',
    ],
  },
  {
    number: 36,
    unit: 6,
    kind: 'mission',
    minutes: 7,
    title: t(
      'Mission · Arrange a meeting',
      'Миссия · Договоритесь о встрече',
      'მისია · დაგეგმეთ შეხვედრა',
    ),
    subtitle: t(
      'Confirm a place and time.',
      'Подтвердите место и время.',
      'დაადასტურეთ ადგილი და დრო.',
    ),
    words: [],
    scenarios: [
      {
        prompt: t(
          'Say you work in an office.',
          'Скажите, что работаете в офисе.',
          'თქვით, რომ ოფისში მუშაობთ.',
        ),
        options: ['ოფისში ვმუშაობ', 'ოფისი ძვირია', 'ოფისში ვიძინებ'],
        correct: 0,
        meaning: t(
          'I work in an office.',
          'Я работаю в офисе.',
          'ოფისში ვმუშაობ.',
        ),
      },
      {
        prompt: t(
          'Ask: “Tomorrow?”',
          'Спросите: «Завтра?»',
          'იკითხეთ: „ხვალ?“',
        ),
        options: ['გუშინ?', 'ხვალ?', 'გვიან?'],
        correct: 1,
        meaning: t('Tomorrow?', 'Завтра?', 'ხვალ?'),
      },
      {
        prompt: t(
          'Say you are waiting here.',
          'Скажите, что ждёте здесь.',
          'თქვით, რომ აქ ელოდებით.',
        ),
        options: ['აქ ველოდები', 'აქ ვპასუხობ', 'აქ ვამთავრებ'],
        correct: 0,
        meaning: t('I am waiting here.', 'Я жду здесь.', 'აქ ველოდები.'),
      },
    ],
  },
  {
    number: 37,
    unit: 7,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Say how you feel',
      'Скажите, как вы себя чувствуете',
      'თქვით, როგორ გრძნობთ თავს',
    ),
    subtitle: t(
      'Explain pain, fever, and a cough.',
      'Объясните боль, температуру и кашель.',
      'ახსენით ტკივილი, სიცხე და ხველა.',
    ),
    words: ['ავად', 'ტკივილი', 'მტკივა', 'ცხელება', 'ხველა'],
  },
  {
    number: 38,
    unit: 7,
    kind: 'lesson',
    minutes: 6,
    title: t('Where it hurts', 'Где болит', 'სად გტკივათ'),
    subtitle: t(
      'Name common parts of the body.',
      'Назовите основные части тела.',
      'დაასახელეთ სხეულის ძირითადი ნაწილები.',
    ),
    words: ['თავი', 'ყელი', 'მუცელი', 'ზურგი', 'კბილი'],
  },
  {
    number: 39,
    unit: 7,
    kind: 'lesson',
    minutes: 6,
    title: t('At the pharmacy', 'В аптеке', 'აფთიაქში'),
    subtitle: t(
      'Ask for a doctor, medicine, or help.',
      'Попросите врача, лекарство или помощь.',
      'ითხოვეთ ექიმი, წამალი ან დახმარება.',
    ),
    words: ['აფთიაქი', 'წამალი', 'ექიმი', 'საავადმყოფო', 'მჭირდება'],
  },
  {
    number: 40,
    unit: 7,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Describe your condition',
      'Опишите состояние',
      'აღწერეთ თქვენი მდგომარეობა',
    ),
    subtitle: t(
      'Say whether you feel cold, tired, or weak.',
      'Скажите, холодно ли вам, устали ли вы или слабы.',
      'თქვით, გცივათ, დაღლილი ხართ თუ სუსტი.',
    ),
    words: ['მცივა', 'მცხელა', 'დაღლილი', 'სუსტი', 'ჯანმრთელი'],
  },
  {
    number: 41,
    unit: 7,
    kind: 'review',
    minutes: 5,
    title: t(
      'Memory Check · Health',
      'Проверка памяти · Здоровье',
      'მეხსიერება · ჯანმრთელობა',
    ),
    subtitle: t(
      'Recall the words you may need quickly.',
      'Вспомните слова, которые могут понадобиться быстро.',
      'გაიხსენეთ სიტყვები, რომლებიც შეიძლება სწრაფად დაგჭირდეთ.',
    ),
    words: [
      'ავად',
      'მტკივა',
      'ცხელება',
      'თავი',
      'ყელი',
      'აფთიაქი',
      'წამალი',
      'ექიმი',
      'მჭირდება',
    ],
  },
  {
    number: 42,
    unit: 7,
    kind: 'mission',
    minutes: 7,
    title: t(
      'Mission · Visit a pharmacy',
      'Миссия · Посетите аптеку',
      'მისია · შედით აფთიაქში',
    ),
    subtitle: t(
      'Explain the problem and ask for help.',
      'Объясните проблему и попросите помощи.',
      'ახსენით პრობლემა და ითხოვეთ დახმარება.',
    ),
    words: [],
    scenarios: [
      {
        prompt: t(
          'Say your head hurts.',
          'Скажите, что у вас болит голова.',
          'თქვით, რომ თავი გტკივათ.',
        ),
        options: ['თავი მტკივა', 'თავი კარგია', 'თავი მინდა'],
        correct: 0,
        meaning: t('My head hurts.', 'У меня болит голова.', 'თავი მტკივა.'),
      },
      {
        prompt: t(
          'Say you need medicine.',
          'Скажите, что вам нужно лекарство.',
          'თქვით, რომ წამალი გჭირდებათ.',
        ),
        options: ['წამალი მჭირდება', 'წამალი შორს არის', 'წამალი არა'],
        correct: 0,
        meaning: t(
          'I need medicine.',
          'Мне нужно лекарство.',
          'წამალი მჭირდება.',
        ),
      },
      {
        prompt: t('Ask for a doctor.', 'Попросите врача.', 'ითხოვეთ ექიმი.'),
        options: ['ექიმი, გთხოვთ', 'ექიმი ძვირია', 'ექიმი ხვალ'],
        correct: 0,
        meaning: t('A doctor, please.', 'Врача, пожалуйста.', 'ექიმი, გთხოვთ.'),
      },
    ],
  },
  {
    number: 43,
    unit: 8,
    kind: 'lesson',
    minutes: 6,
    title: t('People close to you', 'Близкие люди', 'თქვენთან ახლო ადამიანები'),
    subtitle: t(
      'Talk about friends, family, and guests.',
      'Говорите о друзьях, семье и гостях.',
      'ისაუბრეთ მეგობრებზე, ოჯახსა და სტუმრებზე.',
    ),
    words: ['მეგობარი', 'ოჯახი', 'სტუმარი', 'ერთად', 'თავისუფალი'],
  },
  {
    number: 44,
    unit: 8,
    kind: 'lesson',
    minutes: 6,
    title: t('Make a plan', 'Составьте план', 'შეადგინეთ გეგმა'),
    subtitle: t(
      'Choose today, tomorrow, morning, or evening.',
      'Выберите сегодня, завтра, утро или вечер.',
      'აირჩიეთ დღეს, ხვალ, დილა ან საღამო.',
    ),
    words: ['დღეს', 'ხვალ', 'დილა', 'საღამო', 'მოდი'],
  },
  {
    number: 45,
    unit: 8,
    kind: 'lesson',
    minutes: 6,
    title: t(
      'Share what you like',
      'Расскажите, что вам нравится',
      'თქვით, რა მოგწონთ',
    ),
    subtitle: t(
      'React warmly in a conversation.',
      'Тепло отреагируйте в разговоре.',
      'თბილად უპასუხეთ საუბარში.',
    ),
    words: ['მიყვარს', 'მომწონს', 'საინტერესო', 'სასაცილო', 'ბედნიერი'],
  },
  {
    number: 46,
    unit: 8,
    kind: 'lesson',
    minutes: 7,
    title: t('Meet outside', 'Встретьтесь в городе', 'შეხვდით ქალაქში'),
    subtitle: t(
      'Choose a place and wait for a friend.',
      'Выберите место и подождите друга.',
      'აირჩიეთ ადგილი და დაელოდეთ მეგობარს.',
    ),
    words: ['პარკი', 'რესტორანი', 'კაფე', 'ზღვა', 'ველოდები'],
  },
  {
    number: 47,
    unit: 8,
    kind: 'review',
    minutes: 5,
    title: t(
      'Memory Check · Plans',
      'Проверка памяти · Планы',
      'მეხსიერება · გეგმები',
    ),
    subtitle: t(
      'Recall the language for making plans.',
      'Вспомните слова для планов.',
      'გაიხსენეთ გეგმებისთვის საჭირო სიტყვები.',
    ),
    words: [
      'მეგობარი',
      'ოჯახი',
      'ერთად',
      'თავისუფალი',
      'ხვალ',
      'საღამო',
      'მოდი',
      'მომწონს',
      'პარკი',
    ],
  },
  {
    number: 48,
    unit: 8,
    kind: 'mission',
    minutes: 7,
    title: t(
      'Mission · Make a plan',
      'Миссия · Договоритесь о планах',
      'მისია · დაგეგმეთ შეხვედრა',
    ),
    subtitle: t(
      'Invite a friend and choose a place.',
      'Пригласите друга и выберите место.',
      'მოიწვიეთ მეგობარი და აირჩიეთ ადგილი.',
    ),
    words: [],
    scenarios: [
      {
        prompt: t(
          'Ask to meet tomorrow.',
          'Предложите встретиться завтра.',
          'შესთავაზეთ შეხვედრა ხვალ.',
        ),
        options: ['ხვალ ერთად?', 'გუშინ მარტო?', 'დღეს არა'],
        correct: 0,
        meaning: t('Together tomorrow?', 'Вместе завтра?', 'ხვალ ერთად?'),
      },
      {
        prompt: t(
          'Say you like the café.',
          'Скажите, что вам нравится кафе.',
          'თქვით, რომ კაფე მოგწონთ.',
        ),
        options: ['კაფე მომწონს', 'კაფე მტკივა', 'კაფე ვიძინებ'],
        correct: 0,
        meaning: t('I like the café.', 'Мне нравится кафе.', 'კაფე მომწონს.'),
      },
      {
        prompt: t(
          'Say you are waiting in the park.',
          'Скажите, что ждёте в парке.',
          'თქვით, რომ პარკში ელოდებით.',
        ),
        options: ['პარკში ველოდები', 'პარკში ვმუშაობ', 'პარკი შორს'],
        correct: 0,
        meaning: t(
          'I am waiting in the park.',
          'Я жду в парке.',
          'პარკში ველოდები.',
        ),
      },
    ],
  },
];
